return {
    APPLICATION                                     = "/applications/@me",
    APPLICATION_COMMAND                             = "/applications/%s/commands/%s",
    APPLICATION_COMMANDS                            = "/applications/%s/commands",
    APPLICATION_GUILD_COMMAND                       = "/applications/%s/guilds/%s/commands/%s",
    APPLICATION_GUILD_COMMANDS                      = "/applications/%s/guilds/%s/commands",
    APPLICATION_GUILD_COMMAND_PERMISSIONS           = "/applications/%s/guilds/%s/commands/%s/permissions",
    APPLICATION_GUILD_COMMANDS_PERMISSIONS          = "/applications/%s/guilds/%s/commands/permissions",
    APPLICATION_ROLE_CONNECTIONS_METADATA           = "/applications/%s/role-connections/metadata",

    CHANNEL                                         = "/channels/%s",
    CHANNEL_FOLLOWERS                               = "/channels/%s/followers",
    CHANNEL_INVITES                                 = "/channels/%s/invites",
    CHANNEL_MESSAGE                                 = "/channels/%s/messages/%s",
    CHANNEL_MESSAGES                                = "/channels/%s/messages",
    CHANNEL_MESSAGE_CROSSPOST                       = "/channels/%s/messages/%s/crosspost",
    CHANNEL_MESSAGE_REACTION                        = "/channels/%s/messages/%s/reactions/%s/%s",
    CHANNEL_MESSAGE_REACTIONS                       = "/channels/%s/messages/%s/reactions",
    CHANNEL_MESSAGE_REACTION_ME                     = "/channels/%s/messages/%s/reactions/%s/@me",
    CHANNEL_MESSAGE_REACTION_ALL                    = "/channels/%s/messages/%s/reactions/%s",
    CHANNEL_MESSAGE_THREADS                         = "/channels/%s/messages/%s/threads",
    CHANNEL_MESSAGES_DELETE                         = "/channels/%s/messages/bulk-delete",
    CHANNEL_PERMISSION                              = "/channels/%s/permissions/%s",
    CHANNEL_PIN                                     = "/channels/%s/pins/%s",
    CHANNEL_PINS                                    = "/channels/%s/pins",
    CHANNEL_RECIPIENT                               = "/channels/%s/recipients/%s",
    CHANNEL_THREADS                                 = "/channels/%s/threads",
    CHANNEL_THREAD_MEMBER                           = "/channels/%s/thread-members/%s",
    CHANNEL_THREAD_MEMBERS                          = "/channels/%s/thread-members",
    CHANNEL_THREAD_MEMBER_ME                        = "/channels/%s/thread-members/@me",
    CHANNEL_THREADS_ARCHIVED_PUBLIC                 = "/channels/%s/threads/archived/public",
    CHANNEL_THREADS_ARCHIVED_PRIVATE                = "/channels/%s/threads/archived/private",
    CHANNEL_THREADS_ARCHIVED_PRIVATE_ME             = "/channels/%s/users/@me/threads/archived/private",
    CHANNEL_TYPING                                  = "/channels/%s/typing",
    CHANNEL_WEBHOOKS                                = "/channels/%s/webhooks",

    GATEWAY                                         = "/gateway",
    GATEWAY_BOT                                     = "/gateway/bot",

    GUILD                                           = "/guilds/%s",
    GUILDS                                          = "/guilds",
    GUILD_AUDIT_LOGS                                = "/guilds/%s/audit-logs",
    GUILD_AUTO_MODERATION_RULE                      = "/guilds/%s/auto-moderation/rules/%s",
    GUILD_AUTO_MODERATION_RULES                     = "/guilds/%s/auto-moderation/rules",
    GUILD_BAN                                       = "/guilds/%s/bans/%s",
    GUILD_BANS                                      = "/guilds/%s/bans",
    GUILD_CHANNELS                                  = "/guilds/%s/channels",
    GUILD_EMOJI                                     = "/guilds/%s/emojis/%s",
    GUILD_EMOJIS                                    = "/guilds/%s/emojis",
    GUILD_INTEGRATION                               = "/guilds/%s/integrations/%s",
    GUILD_INTEGRATIONS                              = "/guilds/%s/integrations",
    GUILD_INVITES                                   = "/guilds/%s/invites",
    GUILD_MEMBER                                    = "/guilds/%s/members/%s",
    GUILD_MEMBERS                                   = "/guilds/%s/members",
    GUILD_MEMBER_ME                                 = "/guilds/%s/members/@me",
    GUILD_MEMBER_ROLE                               = "/guilds/%s/members/%s/roles/%s",
    GUILD_MEMBERS_SEARCH                            = "/guilds/%s/members/search",
    GUILD_MFA                                       = "/guilds/%s/mfa",
    GUILD_ONBOARDING                                = "/guilds/%s/onboarding",
    GUILD_PREVIEW                                   = "/guilds/%s/preview",
    GUILD_PRUNE                                     = "/guilds/%s/prune",
    GUILD_REGIONS                                   = "/guilds/%s/regions",
    GUILD_ROLE                                      = "/guilds/%s/roles/%s",
    GUILD_ROLES                                     = "/guilds/%s/roles",
    GUILD_SCHEDULED_EVENT                           = "/guilds/%s/scheduled-events/%s",
    GUILD_SCHEDULED_EVENTS                          = "/guilds/%s/scheduled-events",
    GUILD_SCHEDULED_EVENT_USERS                     = "/guilds/%s/scheduled-events/%s/users",
    GUILD_STICKER                                   = "/guilds/%s/stickers/%s",
    GUILD_STICKERS                                  = "/guilds/%s/stickers",
    GUILD_TEMPLATE                                  = "/guilds/%s/templates/%s",
    GUILD_TEMPLATES                                 = "/guilds/%s/templates",
    GUILD_TEMPLATE_ANY                              = "/guilds/templates/%s",
    GUILD_THREADS_ACTIVE                            = "/guilds/%s/threads/active",
    GUILD_VANITY_URL                                = "/guilds/%s/vanity-url",
    GUILD_VOICE_STATES                              = "/guilds/%s/voice-states/%s",
    GUILD_VOICE_STATES_ME                           = "/guilds/%s/voice-states/@me",
    GUILD_WEBHOOKS                                  = "/guilds/%s/webhooks",
    GUILD_WELCOME_SCREEN                            = "/guilds/%s/welcome-screen",
    GUILD_WIDGET                                    = "/guilds/%s/widget",
    GUILD_WIDGET_JSON                               = "/guilds/%s/widget.json",
    GUILD_WIDGET_PNG                                = "/guilds/%s/widget.png",

    INTERACTION                                     = "/webhooks/%s/%s",
    INTERACTION_CALLBACK                            = "/interactions/%s/%s/callback",
    INTERACTION_MESSAGE                             = "/webhooks/%s/%s/messages/%s",
    INTERACTION_MESSAGE_ORIGINAL                    = "/webhooks/%s/%s/messages/@original",

    INVITE                                          = "/invites/%s",

    OAUTH2_ME                                       = "/oauth2/@me",
    OAUTH2_APPLICATION_ME                           = "/oauth2/applications/@me",

    STAGE                                           = "/stage-instances/%s",
    STAGES                                          = "/stage-instances",

    STICKER                                         = "/stickers/%s",
    STICKERS                                        = "/sticker-packs",

    USER                                            = "/users/%s",
    USER_ME                                         = "/users/@me",
    USER_ME_CHANNELS                                = "/users/@me/channels",
    USER_ME_CONNECTIONS                             = "/users/@me/connections",
    USER_ME_GUILD                                   = "/users/@me/guilds/%s",
    USER_ME_GUILDS                                  = "/users/@me/guilds",
    USER_ME_GUILD_MEMBER                            = "/users/@me/guilds/%s/member",
    USER_ME_APPLICATION_ROLE_CONNECTION             = "/users/@me/applications/%s/role-connection",

    VOICE_REGIONS                                   = "/voice/regions",

    WEBHOOK                                         = "/webhooks/%s",
    WEBHOOK_TOKEN                                   = "/webhooks/%s/%s",
    WEBHOOK_TOKEN_MESSAGE                           = "/webhooks/%s/%s/messages/%s",
    WEBHOOK_TOKEN_GITHUB                            = "/webhooks/%s/%s/github",
    WEBHOOK_TOKEN_SLACK                             = "/webhooks/%s/%s/slack",
}